// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/TransportResponse.proto

package com.smileframework.bullet.transport.common.protocol;

public final class TransportResponseProto {
  private TransportResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransportResponseHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransportResponseHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestId = 1;</code>
     * @return The requestId.
     */
    java.lang.String getRequestId();
    /**
     * <code>string requestId = 1;</code>
     * @return The bytes for requestId.
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>int32 operationType = 2;</code>
     * @return The operationType.
     */
    int getOperationType();

    /**
     * <code>int32 contentType = 3;</code>
     * @return The contentType.
     */
    int getContentType();

    /**
     * <code>string actionURL = 4;</code>
     * @return The actionURL.
     */
    java.lang.String getActionURL();
    /**
     * <code>string actionURL = 4;</code>
     * @return The bytes for actionURL.
     */
    com.google.protobuf.ByteString
        getActionURLBytes();

    /**
     * <code>string code = 5;</code>
     * @return The code.
     */
    java.lang.String getCode();
    /**
     * <code>string code = 5;</code>
     * @return The bytes for code.
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>string errorReason = 6;</code>
     * @return The errorReason.
     */
    java.lang.String getErrorReason();
    /**
     * <code>string errorReason = 6;</code>
     * @return The bytes for errorReason.
     */
    com.google.protobuf.ByteString
        getErrorReasonBytes();

    /**
     * <code>string exceptionClz = 7;</code>
     * @return The exceptionClz.
     */
    java.lang.String getExceptionClz();
    /**
     * <code>string exceptionClz = 7;</code>
     * @return The bytes for exceptionClz.
     */
    com.google.protobuf.ByteString
        getExceptionClzBytes();

    /**
     * <code>map&lt;string, string&gt; metadata = 8;</code>
     */
    int getMetadataCount();
    /**
     * <code>map&lt;string, string&gt; metadata = 8;</code>
     */
    boolean containsMetadata(
        java.lang.String key);
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMetadata();
    /**
     * <code>map&lt;string, string&gt; metadata = 8;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMetadataMap();
    /**
     * <code>map&lt;string, string&gt; metadata = 8;</code>
     */
    /* nullable */
java.lang.String getMetadataOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; metadata = 8;</code>
     */
    java.lang.String getMetadataOrThrow(
        java.lang.String key);

    /**
     * <code>string convertDesc = 9;</code>
     * @return The convertDesc.
     */
    java.lang.String getConvertDesc();
    /**
     * <code>string convertDesc = 9;</code>
     * @return The bytes for convertDesc.
     */
    com.google.protobuf.ByteString
        getConvertDescBytes();
  }
  /**
   * Protobuf type {@code TransportResponseHeader}
   */
  public static final class TransportResponseHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransportResponseHeader)
      TransportResponseHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransportResponseHeader.newBuilder() to construct.
    private TransportResponseHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransportResponseHeader() {
      requestId_ = "";
      actionURL_ = "";
      code_ = "";
      errorReason_ = "";
      exceptionClz_ = "";
      convertDesc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransportResponseHeader();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransportResponseProto.internal_static_TransportResponseHeader_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransportResponseProto.internal_static_TransportResponseHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransportResponseProto.TransportResponseHeader.class, TransportResponseProto.TransportResponseHeader.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestId_ = "";
    /**
     * <code>string requestId = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATIONTYPE_FIELD_NUMBER = 2;
    private int operationType_ = 0;
    /**
     * <code>int32 operationType = 2;</code>
     * @return The operationType.
     */
    @java.lang.Override
    public int getOperationType() {
      return operationType_;
    }

    public static final int CONTENTTYPE_FIELD_NUMBER = 3;
    private int contentType_ = 0;
    /**
     * <code>int32 contentType = 3;</code>
     * @return The contentType.
     */
    @java.lang.Override
    public int getContentType() {
      return contentType_;
    }

    public static final int ACTIONURL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object actionURL_ = "";
    /**
     * <code>string actionURL = 4;</code>
     * @return The actionURL.
     */
    @java.lang.Override
    public java.lang.String getActionURL() {
      java.lang.Object ref = actionURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actionURL_ = s;
        return s;
      }
    }
    /**
     * <code>string actionURL = 4;</code>
     * @return The bytes for actionURL.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionURLBytes() {
      java.lang.Object ref = actionURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actionURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object code_ = "";
    /**
     * <code>string code = 5;</code>
     * @return The code.
     */
    @java.lang.Override
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <code>string code = 5;</code>
     * @return The bytes for code.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORREASON_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object errorReason_ = "";
    /**
     * <code>string errorReason = 6;</code>
     * @return The errorReason.
     */
    @java.lang.Override
    public java.lang.String getErrorReason() {
      java.lang.Object ref = errorReason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorReason_ = s;
        return s;
      }
    }
    /**
     * <code>string errorReason = 6;</code>
     * @return The bytes for errorReason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorReasonBytes() {
      java.lang.Object ref = errorReason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCEPTIONCLZ_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object exceptionClz_ = "";
    /**
     * <code>string exceptionClz = 7;</code>
     * @return The exceptionClz.
     */
    @java.lang.Override
    public java.lang.String getExceptionClz() {
      java.lang.Object ref = exceptionClz_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exceptionClz_ = s;
        return s;
      }
    }
    /**
     * <code>string exceptionClz = 7;</code>
     * @return The bytes for exceptionClz.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExceptionClzBytes() {
      java.lang.Object ref = exceptionClz_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exceptionClz_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METADATA_FIELD_NUMBER = 8;
    private static final class MetadataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  TransportResponseProto.internal_static_TransportResponseHeader_MetadataEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metadata_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetadata() {
      if (metadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      return metadata_;
    }
    public int getMetadataCount() {
      return internalGetMetadata().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 8;</code>
     */
    @java.lang.Override
    public boolean containsMetadata(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 8;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
      return internalGetMetadata().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 8;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMetadataOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 8;</code>
     */
    @java.lang.Override
    public java.lang.String getMetadataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int CONVERTDESC_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object convertDesc_ = "";
    /**
     * <code>string convertDesc = 9;</code>
     * @return The convertDesc.
     */
    @java.lang.Override
    public java.lang.String getConvertDesc() {
      java.lang.Object ref = convertDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        convertDesc_ = s;
        return s;
      }
    }
    /**
     * <code>string convertDesc = 9;</code>
     * @return The bytes for convertDesc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConvertDescBytes() {
      java.lang.Object ref = convertDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        convertDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (operationType_ != 0) {
        output.writeInt32(2, operationType_);
      }
      if (contentType_ != 0) {
        output.writeInt32(3, contentType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(actionURL_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, actionURL_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorReason_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, errorReason_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exceptionClz_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, exceptionClz_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMetadata(),
          MetadataDefaultEntryHolder.defaultEntry,
          8);
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(convertDesc_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, convertDesc_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (operationType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, operationType_);
      }
      if (contentType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, contentType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(actionURL_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, actionURL_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorReason_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, errorReason_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exceptionClz_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, exceptionClz_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMetadata().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(8, metadata__);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(convertDesc_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, convertDesc_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TransportResponseProto.TransportResponseHeader)) {
        return super.equals(obj);
      }
      TransportResponseProto.TransportResponseHeader other = (TransportResponseProto.TransportResponseHeader) obj;

      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (getOperationType()
          != other.getOperationType()) return false;
      if (getContentType()
          != other.getContentType()) return false;
      if (!getActionURL()
          .equals(other.getActionURL())) return false;
      if (!getCode()
          .equals(other.getCode())) return false;
      if (!getErrorReason()
          .equals(other.getErrorReason())) return false;
      if (!getExceptionClz()
          .equals(other.getExceptionClz())) return false;
      if (!internalGetMetadata().equals(
          other.internalGetMetadata())) return false;
      if (!getConvertDesc()
          .equals(other.getConvertDesc())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + OPERATIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getOperationType();
      hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getContentType();
      hash = (37 * hash) + ACTIONURL_FIELD_NUMBER;
      hash = (53 * hash) + getActionURL().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + ERRORREASON_FIELD_NUMBER;
      hash = (53 * hash) + getErrorReason().hashCode();
      hash = (37 * hash) + EXCEPTIONCLZ_FIELD_NUMBER;
      hash = (53 * hash) + getExceptionClz().hashCode();
      if (!internalGetMetadata().getMap().isEmpty()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMetadata().hashCode();
      }
      hash = (37 * hash) + CONVERTDESC_FIELD_NUMBER;
      hash = (53 * hash) + getConvertDesc().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TransportResponseProto.TransportResponseHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportResponseProto.TransportResponseHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportResponseProto.TransportResponseHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportResponseProto.TransportResponseHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportResponseProto.TransportResponseHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportResponseProto.TransportResponseHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportResponseProto.TransportResponseHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransportResponseProto.TransportResponseHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransportResponseProto.TransportResponseHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TransportResponseProto.TransportResponseHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransportResponseProto.TransportResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransportResponseProto.TransportResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TransportResponseProto.TransportResponseHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransportResponseHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransportResponseHeader)
        TransportResponseProto.TransportResponseHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransportResponseProto.internal_static_TransportResponseHeader_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetMutableMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransportResponseProto.internal_static_TransportResponseHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransportResponseProto.TransportResponseHeader.class, TransportResponseProto.TransportResponseHeader.Builder.class);
      }

      // Construct using com.reabam.framework.bullet.transport.common.protocol.TransportResponseProto.TransportResponseHeader.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestId_ = "";
        operationType_ = 0;
        contentType_ = 0;
        actionURL_ = "";
        code_ = "";
        errorReason_ = "";
        exceptionClz_ = "";
        internalGetMutableMetadata().clear();
        convertDesc_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransportResponseProto.internal_static_TransportResponseHeader_descriptor;
      }

      @java.lang.Override
      public TransportResponseProto.TransportResponseHeader getDefaultInstanceForType() {
        return TransportResponseProto.TransportResponseHeader.getDefaultInstance();
      }

      @java.lang.Override
      public TransportResponseProto.TransportResponseHeader build() {
        TransportResponseProto.TransportResponseHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TransportResponseProto.TransportResponseHeader buildPartial() {
        TransportResponseProto.TransportResponseHeader result = new TransportResponseProto.TransportResponseHeader(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(TransportResponseProto.TransportResponseHeader result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestId_ = requestId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.operationType_ = operationType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.contentType_ = contentType_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.actionURL_ = actionURL_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.errorReason_ = errorReason_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.exceptionClz_ = exceptionClz_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.metadata_ = internalGetMetadata();
          result.metadata_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.convertDesc_ = convertDesc_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransportResponseProto.TransportResponseHeader) {
          return mergeFrom((TransportResponseProto.TransportResponseHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransportResponseProto.TransportResponseHeader other) {
        if (other == TransportResponseProto.TransportResponseHeader.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getOperationType() != 0) {
          setOperationType(other.getOperationType());
        }
        if (other.getContentType() != 0) {
          setContentType(other.getContentType());
        }
        if (!other.getActionURL().isEmpty()) {
          actionURL_ = other.actionURL_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getErrorReason().isEmpty()) {
          errorReason_ = other.errorReason_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getExceptionClz().isEmpty()) {
          exceptionClz_ = other.exceptionClz_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        internalGetMutableMetadata().mergeFrom(
            other.internalGetMetadata());
        bitField0_ |= 0x00000080;
        if (!other.getConvertDesc().isEmpty()) {
          convertDesc_ = other.convertDesc_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                requestId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                operationType_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                contentType_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                actionURL_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                code_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                errorReason_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                exceptionClz_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                metadata__ = input.readMessage(
                    MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableMetadata().getMutableMap().put(
                    metadata__.getKey(), metadata__.getValue());
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                convertDesc_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestId_ = "";
      /**
       * <code>string requestId = 1;</code>
       * @return The requestId.
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       * @return The bytes for requestId.
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        requestId_ = getDefaultInstance().getRequestId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       * @param value The bytes for requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int operationType_ ;
      /**
       * <code>int32 operationType = 2;</code>
       * @return The operationType.
       */
      @java.lang.Override
      public int getOperationType() {
        return operationType_;
      }
      /**
       * <code>int32 operationType = 2;</code>
       * @param value The operationType to set.
       * @return This builder for chaining.
       */
      public Builder setOperationType(int value) {

        operationType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 operationType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperationType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        operationType_ = 0;
        onChanged();
        return this;
      }

      private int contentType_ ;
      /**
       * <code>int32 contentType = 3;</code>
       * @return The contentType.
       */
      @java.lang.Override
      public int getContentType() {
        return contentType_;
      }
      /**
       * <code>int32 contentType = 3;</code>
       * @param value The contentType to set.
       * @return This builder for chaining.
       */
      public Builder setContentType(int value) {

        contentType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 contentType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContentType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        contentType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object actionURL_ = "";
      /**
       * <code>string actionURL = 4;</code>
       * @return The actionURL.
       */
      public java.lang.String getActionURL() {
        java.lang.Object ref = actionURL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          actionURL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string actionURL = 4;</code>
       * @return The bytes for actionURL.
       */
      public com.google.protobuf.ByteString
          getActionURLBytes() {
        java.lang.Object ref = actionURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actionURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string actionURL = 4;</code>
       * @param value The actionURL to set.
       * @return This builder for chaining.
       */
      public Builder setActionURL(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        actionURL_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string actionURL = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearActionURL() {
        actionURL_ = getDefaultInstance().getActionURL();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string actionURL = 4;</code>
       * @param value The bytes for actionURL to set.
       * @return This builder for chaining.
       */
      public Builder setActionURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        actionURL_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <code>string code = 5;</code>
       * @return The code.
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string code = 5;</code>
       * @return The bytes for code.
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string code = 5;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        code_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string code = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        code_ = getDefaultInstance().getCode();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string code = 5;</code>
       * @param value The bytes for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        code_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object errorReason_ = "";
      /**
       * <code>string errorReason = 6;</code>
       * @return The errorReason.
       */
      public java.lang.String getErrorReason() {
        java.lang.Object ref = errorReason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorReason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string errorReason = 6;</code>
       * @return The bytes for errorReason.
       */
      public com.google.protobuf.ByteString
          getErrorReasonBytes() {
        java.lang.Object ref = errorReason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorReason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errorReason = 6;</code>
       * @param value The errorReason to set.
       * @return This builder for chaining.
       */
      public Builder setErrorReason(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        errorReason_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string errorReason = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorReason() {
        errorReason_ = getDefaultInstance().getErrorReason();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string errorReason = 6;</code>
       * @param value The bytes for errorReason to set.
       * @return This builder for chaining.
       */
      public Builder setErrorReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        errorReason_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object exceptionClz_ = "";
      /**
       * <code>string exceptionClz = 7;</code>
       * @return The exceptionClz.
       */
      public java.lang.String getExceptionClz() {
        java.lang.Object ref = exceptionClz_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exceptionClz_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exceptionClz = 7;</code>
       * @return The bytes for exceptionClz.
       */
      public com.google.protobuf.ByteString
          getExceptionClzBytes() {
        java.lang.Object ref = exceptionClz_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exceptionClz_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exceptionClz = 7;</code>
       * @param value The exceptionClz to set.
       * @return This builder for chaining.
       */
      public Builder setExceptionClz(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        exceptionClz_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string exceptionClz = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearExceptionClz() {
        exceptionClz_ = getDefaultInstance().getExceptionClz();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string exceptionClz = 7;</code>
       * @param value The bytes for exceptionClz to set.
       * @return This builder for chaining.
       */
      public Builder setExceptionClzBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        exceptionClz_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> metadata_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMetadata() {
        if (metadata_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        return metadata_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableMetadata() {
        if (metadata_ == null) {
          metadata_ = com.google.protobuf.MapField.newMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        if (!metadata_.isMutable()) {
          metadata_ = metadata_.copy();
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return metadata_;
      }
      public int getMetadataCount() {
        return internalGetMetadata().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 8;</code>
       */
      @java.lang.Override
      public boolean containsMetadata(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetMetadata().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetadataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
        return getMetadataMap();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 8;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
        return internalGetMetadata().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 8;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getMetadataOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetadata().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 8;</code>
       */
      @java.lang.Override
      public java.lang.String getMetadataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetadata().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearMetadata() {
        bitField0_ = (bitField0_ & ~0x00000080);
        internalGetMutableMetadata().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 8;</code>
       */
      public Builder removeMetadata(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableMetadata().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableMetadata() {
        bitField0_ |= 0x00000080;
        return internalGetMutableMetadata().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 8;</code>
       */
      public Builder putMetadata(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableMetadata().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 8;</code>
       */
      public Builder putAllMetadata(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMetadata().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000080;
        return this;
      }

      private java.lang.Object convertDesc_ = "";
      /**
       * <code>string convertDesc = 9;</code>
       * @return The convertDesc.
       */
      public java.lang.String getConvertDesc() {
        java.lang.Object ref = convertDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          convertDesc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string convertDesc = 9;</code>
       * @return The bytes for convertDesc.
       */
      public com.google.protobuf.ByteString
          getConvertDescBytes() {
        java.lang.Object ref = convertDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          convertDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string convertDesc = 9;</code>
       * @param value The convertDesc to set.
       * @return This builder for chaining.
       */
      public Builder setConvertDesc(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        convertDesc_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string convertDesc = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearConvertDesc() {
        convertDesc_ = getDefaultInstance().getConvertDesc();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string convertDesc = 9;</code>
       * @param value The bytes for convertDesc to set.
       * @return This builder for chaining.
       */
      public Builder setConvertDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        convertDesc_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransportResponseHeader)
    }

    // @@protoc_insertion_point(class_scope:TransportResponseHeader)
    private static final TransportResponseProto.TransportResponseHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TransportResponseProto.TransportResponseHeader();
    }

    public static TransportResponseProto.TransportResponseHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransportResponseHeader>
        PARSER = new com.google.protobuf.AbstractParser<TransportResponseHeader>() {
      @java.lang.Override
      public TransportResponseHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TransportResponseHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransportResponseHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TransportResponseProto.TransportResponseHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransportResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransportResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.TransportResponseHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.TransportResponseHeader header = 1;</code>
     * @return The header.
     */
    TransportResponseProto.TransportResponseHeader getHeader();
    /**
     * <code>.TransportResponseHeader header = 1;</code>
     */
    TransportResponseProto.TransportResponseHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>bytes response = 2;</code>
     * @return The response.
     */
    com.google.protobuf.ByteString getResponse();
  }
  /**
   * Protobuf type {@code TransportResponse}
   */
  public static final class TransportResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransportResponse)
      TransportResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransportResponse.newBuilder() to construct.
    private TransportResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransportResponse() {
      response_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransportResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransportResponseProto.internal_static_TransportResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransportResponseProto.internal_static_TransportResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransportResponseProto.TransportResponse.class, TransportResponseProto.TransportResponse.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private TransportResponseProto.TransportResponseHeader header_;
    /**
     * <code>.TransportResponseHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.TransportResponseHeader header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public TransportResponseProto.TransportResponseHeader getHeader() {
      return header_ == null ? TransportResponseProto.TransportResponseHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.TransportResponseHeader header = 1;</code>
     */
    @java.lang.Override
    public TransportResponseProto.TransportResponseHeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? TransportResponseProto.TransportResponseHeader.getDefaultInstance() : header_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes response = 2;</code>
     * @return The response.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getResponse() {
      return response_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!response_.isEmpty()) {
        output.writeBytes(2, response_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!response_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, response_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TransportResponseProto.TransportResponse)) {
        return super.equals(obj);
      }
      TransportResponseProto.TransportResponse other = (TransportResponseProto.TransportResponse) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getResponse()
          .equals(other.getResponse())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TransportResponseProto.TransportResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportResponseProto.TransportResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportResponseProto.TransportResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportResponseProto.TransportResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportResponseProto.TransportResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportResponseProto.TransportResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportResponseProto.TransportResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransportResponseProto.TransportResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransportResponseProto.TransportResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TransportResponseProto.TransportResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransportResponseProto.TransportResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransportResponseProto.TransportResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TransportResponseProto.TransportResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransportResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransportResponse)
        TransportResponseProto.TransportResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransportResponseProto.internal_static_TransportResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransportResponseProto.internal_static_TransportResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransportResponseProto.TransportResponse.class, TransportResponseProto.TransportResponse.Builder.class);
      }

      // Construct using com.reabam.framework.bullet.transport.common.protocol.TransportResponseProto.TransportResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        response_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransportResponseProto.internal_static_TransportResponse_descriptor;
      }

      @java.lang.Override
      public TransportResponseProto.TransportResponse getDefaultInstanceForType() {
        return TransportResponseProto.TransportResponse.getDefaultInstance();
      }

      @java.lang.Override
      public TransportResponseProto.TransportResponse build() {
        TransportResponseProto.TransportResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TransportResponseProto.TransportResponse buildPartial() {
        TransportResponseProto.TransportResponse result = new TransportResponseProto.TransportResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(TransportResponseProto.TransportResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.header_ = headerBuilder_ == null
              ? header_
              : headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.response_ = response_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransportResponseProto.TransportResponse) {
          return mergeFrom((TransportResponseProto.TransportResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransportResponseProto.TransportResponse other) {
        if (other == TransportResponseProto.TransportResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getResponse() != com.google.protobuf.ByteString.EMPTY) {
          setResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getHeaderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                response_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private TransportResponseProto.TransportResponseHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          TransportResponseProto.TransportResponseHeader, TransportResponseProto.TransportResponseHeader.Builder, TransportResponseProto.TransportResponseHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.TransportResponseHeader header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.TransportResponseHeader header = 1;</code>
       * @return The header.
       */
      public TransportResponseProto.TransportResponseHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? TransportResponseProto.TransportResponseHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.TransportResponseHeader header = 1;</code>
       */
      public Builder setHeader(TransportResponseProto.TransportResponseHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.TransportResponseHeader header = 1;</code>
       */
      public Builder setHeader(
          TransportResponseProto.TransportResponseHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.TransportResponseHeader header = 1;</code>
       */
      public Builder mergeHeader(TransportResponseProto.TransportResponseHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            header_ != null &&
            header_ != TransportResponseProto.TransportResponseHeader.getDefaultInstance()) {
            getHeaderBuilder().mergeFrom(value);
          } else {
            header_ = value;
          }
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.TransportResponseHeader header = 1;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.TransportResponseHeader header = 1;</code>
       */
      public TransportResponseProto.TransportResponseHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.TransportResponseHeader header = 1;</code>
       */
      public TransportResponseProto.TransportResponseHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              TransportResponseProto.TransportResponseHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.TransportResponseHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TransportResponseProto.TransportResponseHeader, TransportResponseProto.TransportResponseHeader.Builder, TransportResponseProto.TransportResponseHeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TransportResponseProto.TransportResponseHeader, TransportResponseProto.TransportResponseHeader.Builder, TransportResponseProto.TransportResponseHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes response = 2;</code>
       * @return The response.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getResponse() {
        return response_;
      }
      /**
       * <code>bytes response = 2;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        response_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes response = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000002);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransportResponse)
    }

    // @@protoc_insertion_point(class_scope:TransportResponse)
    private static final TransportResponseProto.TransportResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TransportResponseProto.TransportResponse();
    }

    public static TransportResponseProto.TransportResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransportResponse>
        PARSER = new com.google.protobuf.AbstractParser<TransportResponse>() {
      @java.lang.Override
      public TransportResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TransportResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransportResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TransportResponseProto.TransportResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransportResponseHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransportResponseHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransportResponseHeader_MetadataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransportResponseHeader_MetadataEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransportResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransportResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"main/proto/TransportResponse.proto\"\244\002\n" +
      "\027TransportResponseHeader\022\021\n\trequestId\030\001 " +
      "\001(\t\022\025\n\roperationType\030\002 \001(\005\022\023\n\013contentTyp" +
      "e\030\003 \001(\005\022\021\n\tactionURL\030\004 \001(\t\022\014\n\004code\030\005 \001(\t" +
      "\022\023\n\013errorReason\030\006 \001(\t\022\024\n\014exceptionClz\030\007 " +
      "\001(\t\0228\n\010metadata\030\010 \003(\0132&.TransportRespons" +
      "eHeader.MetadataEntry\022\023\n\013convertDesc\030\t \001" +
      "(\t\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001\"O\n\021TransportResponse\022(\n\006head" +
      "er\030\001 \001(\0132\030.TransportResponseHeader\022\020\n\010re" +
      "sponse\030\002 \001(\014BO\n5com.reabam.framework.bul" +
      "let.transport.common.protocolB\026Transport" +
      "ResponseProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TransportResponseHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransportResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransportResponseHeader_descriptor,
        new java.lang.String[] { "RequestId", "OperationType", "ContentType", "ActionURL", "Code", "ErrorReason", "ExceptionClz", "Metadata", "ConvertDesc", });
    internal_static_TransportResponseHeader_MetadataEntry_descriptor =
      internal_static_TransportResponseHeader_descriptor.getNestedTypes().get(0);
    internal_static_TransportResponseHeader_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransportResponseHeader_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_TransportResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TransportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransportResponse_descriptor,
        new java.lang.String[] { "Header", "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
