// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/TransportRequest.proto

package com.smileframework.bullet.transport.common.protocol;

public final class TransportRequestProto {
  private TransportRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransportRequestHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransportRequestHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestId = 1;</code>
     * @return The requestId.
     */
    java.lang.String getRequestId();
    /**
     * <code>string requestId = 1;</code>
     * @return The bytes for requestId.
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>int32 operationType = 2;</code>
     * @return The operationType.
     */
    int getOperationType();

    /**
     * <code>int32 contentType = 3;</code>
     * @return The contentType.
     */
    int getContentType();

    /**
     * <code>string authorization = 4;</code>
     * @return The authorization.
     */
    java.lang.String getAuthorization();
    /**
     * <code>string authorization = 4;</code>
     * @return The bytes for authorization.
     */
    com.google.protobuf.ByteString
        getAuthorizationBytes();

    /**
     * <code>string actionURL = 5;</code>
     * @return The actionURL.
     */
    java.lang.String getActionURL();
    /**
     * <code>string actionURL = 5;</code>
     * @return The bytes for actionURL.
     */
    com.google.protobuf.ByteString
        getActionURLBytes();

    /**
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    int getMetadataCount();
    /**
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    boolean containsMetadata(
        java.lang.String key);
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMetadata();
    /**
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMetadataMap();
    /**
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    /* nullable */
java.lang.String getMetadataOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    java.lang.String getMetadataOrThrow(
        java.lang.String key);

    /**
     * <code>string convertDesc = 7;</code>
     * @return The convertDesc.
     */
    java.lang.String getConvertDesc();
    /**
     * <code>string convertDesc = 7;</code>
     * @return The bytes for convertDesc.
     */
    com.google.protobuf.ByteString
        getConvertDescBytes();
  }
  /**
   * Protobuf type {@code TransportRequestHeader}
   */
  public static final class TransportRequestHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransportRequestHeader)
      TransportRequestHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransportRequestHeader.newBuilder() to construct.
    private TransportRequestHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransportRequestHeader() {
      requestId_ = "";
      authorization_ = "";
      actionURL_ = "";
      convertDesc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransportRequestHeader();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransportRequestProto.internal_static_TransportRequestHeader_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransportRequestProto.internal_static_TransportRequestHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransportRequestProto.TransportRequestHeader.class, TransportRequestProto.TransportRequestHeader.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestId_ = "";
    /**
     * <code>string requestId = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATIONTYPE_FIELD_NUMBER = 2;
    private int operationType_ = 0;
    /**
     * <code>int32 operationType = 2;</code>
     * @return The operationType.
     */
    @java.lang.Override
    public int getOperationType() {
      return operationType_;
    }

    public static final int CONTENTTYPE_FIELD_NUMBER = 3;
    private int contentType_ = 0;
    /**
     * <code>int32 contentType = 3;</code>
     * @return The contentType.
     */
    @java.lang.Override
    public int getContentType() {
      return contentType_;
    }

    public static final int AUTHORIZATION_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object authorization_ = "";
    /**
     * <code>string authorization = 4;</code>
     * @return The authorization.
     */
    @java.lang.Override
    public java.lang.String getAuthorization() {
      java.lang.Object ref = authorization_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorization_ = s;
        return s;
      }
    }
    /**
     * <code>string authorization = 4;</code>
     * @return The bytes for authorization.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorizationBytes() {
      java.lang.Object ref = authorization_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorization_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIONURL_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object actionURL_ = "";
    /**
     * <code>string actionURL = 5;</code>
     * @return The actionURL.
     */
    @java.lang.Override
    public java.lang.String getActionURL() {
      java.lang.Object ref = actionURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actionURL_ = s;
        return s;
      }
    }
    /**
     * <code>string actionURL = 5;</code>
     * @return The bytes for actionURL.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionURLBytes() {
      java.lang.Object ref = actionURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actionURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METADATA_FIELD_NUMBER = 6;
    private static final class MetadataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  TransportRequestProto.internal_static_TransportRequestHeader_MetadataEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metadata_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetadata() {
      if (metadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      return metadata_;
    }
    public int getMetadataCount() {
      return internalGetMetadata().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    @java.lang.Override
    public boolean containsMetadata(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
      return internalGetMetadata().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMetadataOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 6;</code>
     */
    @java.lang.Override
    public java.lang.String getMetadataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int CONVERTDESC_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object convertDesc_ = "";
    /**
     * <code>string convertDesc = 7;</code>
     * @return The convertDesc.
     */
    @java.lang.Override
    public java.lang.String getConvertDesc() {
      java.lang.Object ref = convertDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        convertDesc_ = s;
        return s;
      }
    }
    /**
     * <code>string convertDesc = 7;</code>
     * @return The bytes for convertDesc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConvertDescBytes() {
      java.lang.Object ref = convertDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        convertDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (operationType_ != 0) {
        output.writeInt32(2, operationType_);
      }
      if (contentType_ != 0) {
        output.writeInt32(3, contentType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authorization_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, authorization_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(actionURL_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, actionURL_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMetadata(),
          MetadataDefaultEntryHolder.defaultEntry,
          6);
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(convertDesc_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, convertDesc_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (operationType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, operationType_);
      }
      if (contentType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, contentType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authorization_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, authorization_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(actionURL_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, actionURL_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMetadata().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, metadata__);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(convertDesc_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, convertDesc_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TransportRequestProto.TransportRequestHeader)) {
        return super.equals(obj);
      }
      TransportRequestProto.TransportRequestHeader other = (TransportRequestProto.TransportRequestHeader) obj;

      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (getOperationType()
          != other.getOperationType()) return false;
      if (getContentType()
          != other.getContentType()) return false;
      if (!getAuthorization()
          .equals(other.getAuthorization())) return false;
      if (!getActionURL()
          .equals(other.getActionURL())) return false;
      if (!internalGetMetadata().equals(
          other.internalGetMetadata())) return false;
      if (!getConvertDesc()
          .equals(other.getConvertDesc())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + OPERATIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getOperationType();
      hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getContentType();
      hash = (37 * hash) + AUTHORIZATION_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorization().hashCode();
      hash = (37 * hash) + ACTIONURL_FIELD_NUMBER;
      hash = (53 * hash) + getActionURL().hashCode();
      if (!internalGetMetadata().getMap().isEmpty()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMetadata().hashCode();
      }
      hash = (37 * hash) + CONVERTDESC_FIELD_NUMBER;
      hash = (53 * hash) + getConvertDesc().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TransportRequestProto.TransportRequestHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportRequestProto.TransportRequestHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportRequestProto.TransportRequestHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportRequestProto.TransportRequestHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportRequestProto.TransportRequestHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportRequestProto.TransportRequestHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportRequestProto.TransportRequestHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransportRequestProto.TransportRequestHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransportRequestProto.TransportRequestHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TransportRequestProto.TransportRequestHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransportRequestProto.TransportRequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransportRequestProto.TransportRequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TransportRequestProto.TransportRequestHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransportRequestHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransportRequestHeader)
        TransportRequestProto.TransportRequestHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransportRequestProto.internal_static_TransportRequestHeader_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransportRequestProto.internal_static_TransportRequestHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransportRequestProto.TransportRequestHeader.class, TransportRequestProto.TransportRequestHeader.Builder.class);
      }

      // Construct using com.reabam.framework.bullet.transport.common.protocol.TransportRequestProto.TransportRequestHeader.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestId_ = "";
        operationType_ = 0;
        contentType_ = 0;
        authorization_ = "";
        actionURL_ = "";
        internalGetMutableMetadata().clear();
        convertDesc_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransportRequestProto.internal_static_TransportRequestHeader_descriptor;
      }

      @java.lang.Override
      public TransportRequestProto.TransportRequestHeader getDefaultInstanceForType() {
        return TransportRequestProto.TransportRequestHeader.getDefaultInstance();
      }

      @java.lang.Override
      public TransportRequestProto.TransportRequestHeader build() {
        TransportRequestProto.TransportRequestHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TransportRequestProto.TransportRequestHeader buildPartial() {
        TransportRequestProto.TransportRequestHeader result = new TransportRequestProto.TransportRequestHeader(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(TransportRequestProto.TransportRequestHeader result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestId_ = requestId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.operationType_ = operationType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.contentType_ = contentType_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.authorization_ = authorization_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.actionURL_ = actionURL_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.metadata_ = internalGetMetadata();
          result.metadata_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.convertDesc_ = convertDesc_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransportRequestProto.TransportRequestHeader) {
          return mergeFrom((TransportRequestProto.TransportRequestHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransportRequestProto.TransportRequestHeader other) {
        if (other == TransportRequestProto.TransportRequestHeader.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getOperationType() != 0) {
          setOperationType(other.getOperationType());
        }
        if (other.getContentType() != 0) {
          setContentType(other.getContentType());
        }
        if (!other.getAuthorization().isEmpty()) {
          authorization_ = other.authorization_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getActionURL().isEmpty()) {
          actionURL_ = other.actionURL_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        internalGetMutableMetadata().mergeFrom(
            other.internalGetMetadata());
        bitField0_ |= 0x00000020;
        if (!other.getConvertDesc().isEmpty()) {
          convertDesc_ = other.convertDesc_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                requestId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                operationType_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                contentType_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                authorization_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                actionURL_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                metadata__ = input.readMessage(
                    MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableMetadata().getMutableMap().put(
                    metadata__.getKey(), metadata__.getValue());
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                convertDesc_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestId_ = "";
      /**
       * <code>string requestId = 1;</code>
       * @return The requestId.
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       * @return The bytes for requestId.
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        requestId_ = getDefaultInstance().getRequestId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       * @param value The bytes for requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int operationType_ ;
      /**
       * <code>int32 operationType = 2;</code>
       * @return The operationType.
       */
      @java.lang.Override
      public int getOperationType() {
        return operationType_;
      }
      /**
       * <code>int32 operationType = 2;</code>
       * @param value The operationType to set.
       * @return This builder for chaining.
       */
      public Builder setOperationType(int value) {

        operationType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 operationType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperationType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        operationType_ = 0;
        onChanged();
        return this;
      }

      private int contentType_ ;
      /**
       * <code>int32 contentType = 3;</code>
       * @return The contentType.
       */
      @java.lang.Override
      public int getContentType() {
        return contentType_;
      }
      /**
       * <code>int32 contentType = 3;</code>
       * @param value The contentType to set.
       * @return This builder for chaining.
       */
      public Builder setContentType(int value) {

        contentType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 contentType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContentType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        contentType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object authorization_ = "";
      /**
       * <code>string authorization = 4;</code>
       * @return The authorization.
       */
      public java.lang.String getAuthorization() {
        java.lang.Object ref = authorization_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authorization_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string authorization = 4;</code>
       * @return The bytes for authorization.
       */
      public com.google.protobuf.ByteString
          getAuthorizationBytes() {
        java.lang.Object ref = authorization_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authorization_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authorization = 4;</code>
       * @param value The authorization to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorization(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        authorization_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string authorization = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorization() {
        authorization_ = getDefaultInstance().getAuthorization();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string authorization = 4;</code>
       * @param value The bytes for authorization to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        authorization_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object actionURL_ = "";
      /**
       * <code>string actionURL = 5;</code>
       * @return The actionURL.
       */
      public java.lang.String getActionURL() {
        java.lang.Object ref = actionURL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          actionURL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string actionURL = 5;</code>
       * @return The bytes for actionURL.
       */
      public com.google.protobuf.ByteString
          getActionURLBytes() {
        java.lang.Object ref = actionURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actionURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string actionURL = 5;</code>
       * @param value The actionURL to set.
       * @return This builder for chaining.
       */
      public Builder setActionURL(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        actionURL_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string actionURL = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearActionURL() {
        actionURL_ = getDefaultInstance().getActionURL();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string actionURL = 5;</code>
       * @param value The bytes for actionURL to set.
       * @return This builder for chaining.
       */
      public Builder setActionURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        actionURL_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> metadata_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMetadata() {
        if (metadata_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        return metadata_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableMetadata() {
        if (metadata_ == null) {
          metadata_ = com.google.protobuf.MapField.newMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        if (!metadata_.isMutable()) {
          metadata_ = metadata_.copy();
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return metadata_;
      }
      public int getMetadataCount() {
        return internalGetMetadata().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 6;</code>
       */
      @java.lang.Override
      public boolean containsMetadata(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetMetadata().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetadataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
        return getMetadataMap();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 6;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
        return internalGetMetadata().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 6;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getMetadataOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetadata().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 6;</code>
       */
      @java.lang.Override
      public java.lang.String getMetadataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetadata().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearMetadata() {
        bitField0_ = (bitField0_ & ~0x00000020);
        internalGetMutableMetadata().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 6;</code>
       */
      public Builder removeMetadata(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableMetadata().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableMetadata() {
        bitField0_ |= 0x00000020;
        return internalGetMutableMetadata().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 6;</code>
       */
      public Builder putMetadata(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableMetadata().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; metadata = 6;</code>
       */
      public Builder putAllMetadata(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMetadata().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000020;
        return this;
      }

      private java.lang.Object convertDesc_ = "";
      /**
       * <code>string convertDesc = 7;</code>
       * @return The convertDesc.
       */
      public java.lang.String getConvertDesc() {
        java.lang.Object ref = convertDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          convertDesc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string convertDesc = 7;</code>
       * @return The bytes for convertDesc.
       */
      public com.google.protobuf.ByteString
          getConvertDescBytes() {
        java.lang.Object ref = convertDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          convertDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string convertDesc = 7;</code>
       * @param value The convertDesc to set.
       * @return This builder for chaining.
       */
      public Builder setConvertDesc(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        convertDesc_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string convertDesc = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearConvertDesc() {
        convertDesc_ = getDefaultInstance().getConvertDesc();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string convertDesc = 7;</code>
       * @param value The bytes for convertDesc to set.
       * @return This builder for chaining.
       */
      public Builder setConvertDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        convertDesc_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransportRequestHeader)
    }

    // @@protoc_insertion_point(class_scope:TransportRequestHeader)
    private static final TransportRequestProto.TransportRequestHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TransportRequestProto.TransportRequestHeader();
    }

    public static TransportRequestProto.TransportRequestHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransportRequestHeader>
        PARSER = new com.google.protobuf.AbstractParser<TransportRequestHeader>() {
      @java.lang.Override
      public TransportRequestHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TransportRequestHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransportRequestHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TransportRequestProto.TransportRequestHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransportRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransportRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.TransportRequestHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.TransportRequestHeader header = 1;</code>
     * @return The header.
     */
    TransportRequestProto.TransportRequestHeader getHeader();
    /**
     * <code>.TransportRequestHeader header = 1;</code>
     */
    TransportRequestProto.TransportRequestHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code TransportRequest}
   */
  public static final class TransportRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransportRequest)
      TransportRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransportRequest.newBuilder() to construct.
    private TransportRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransportRequest() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransportRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransportRequestProto.internal_static_TransportRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransportRequestProto.internal_static_TransportRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransportRequestProto.TransportRequest.class, TransportRequestProto.TransportRequest.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private TransportRequestProto.TransportRequestHeader header_;
    /**
     * <code>.TransportRequestHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.TransportRequestHeader header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public TransportRequestProto.TransportRequestHeader getHeader() {
      return header_ == null ? TransportRequestProto.TransportRequestHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.TransportRequestHeader header = 1;</code>
     */
    @java.lang.Override
    public TransportRequestProto.TransportRequestHeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? TransportRequestProto.TransportRequestHeader.getDefaultInstance() : header_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(2, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TransportRequestProto.TransportRequest)) {
        return super.equals(obj);
      }
      TransportRequestProto.TransportRequest other = (TransportRequestProto.TransportRequest) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TransportRequestProto.TransportRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportRequestProto.TransportRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportRequestProto.TransportRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportRequestProto.TransportRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportRequestProto.TransportRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransportRequestProto.TransportRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransportRequestProto.TransportRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransportRequestProto.TransportRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransportRequestProto.TransportRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TransportRequestProto.TransportRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransportRequestProto.TransportRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TransportRequestProto.TransportRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TransportRequestProto.TransportRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransportRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransportRequest)
        TransportRequestProto.TransportRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransportRequestProto.internal_static_TransportRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransportRequestProto.internal_static_TransportRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TransportRequestProto.TransportRequest.class, TransportRequestProto.TransportRequest.Builder.class);
      }

      // Construct using com.reabam.framework.bullet.transport.common.protocol.TransportRequestProto.TransportRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        payload_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransportRequestProto.internal_static_TransportRequest_descriptor;
      }

      @java.lang.Override
      public TransportRequestProto.TransportRequest getDefaultInstanceForType() {
        return TransportRequestProto.TransportRequest.getDefaultInstance();
      }

      @java.lang.Override
      public TransportRequestProto.TransportRequest build() {
        TransportRequestProto.TransportRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TransportRequestProto.TransportRequest buildPartial() {
        TransportRequestProto.TransportRequest result = new TransportRequestProto.TransportRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(TransportRequestProto.TransportRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.header_ = headerBuilder_ == null
              ? header_
              : headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.payload_ = payload_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransportRequestProto.TransportRequest) {
          return mergeFrom((TransportRequestProto.TransportRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransportRequestProto.TransportRequest other) {
        if (other == TransportRequestProto.TransportRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getHeaderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private TransportRequestProto.TransportRequestHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          TransportRequestProto.TransportRequestHeader, TransportRequestProto.TransportRequestHeader.Builder, TransportRequestProto.TransportRequestHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.TransportRequestHeader header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.TransportRequestHeader header = 1;</code>
       * @return The header.
       */
      public TransportRequestProto.TransportRequestHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? TransportRequestProto.TransportRequestHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.TransportRequestHeader header = 1;</code>
       */
      public Builder setHeader(TransportRequestProto.TransportRequestHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.TransportRequestHeader header = 1;</code>
       */
      public Builder setHeader(
          TransportRequestProto.TransportRequestHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.TransportRequestHeader header = 1;</code>
       */
      public Builder mergeHeader(TransportRequestProto.TransportRequestHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            header_ != null &&
            header_ != TransportRequestProto.TransportRequestHeader.getDefaultInstance()) {
            getHeaderBuilder().mergeFrom(value);
          } else {
            header_ = value;
          }
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.TransportRequestHeader header = 1;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.TransportRequestHeader header = 1;</code>
       */
      public TransportRequestProto.TransportRequestHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.TransportRequestHeader header = 1;</code>
       */
      public TransportRequestProto.TransportRequestHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              TransportRequestProto.TransportRequestHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.TransportRequestHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TransportRequestProto.TransportRequestHeader, TransportRequestProto.TransportRequestHeader.Builder, TransportRequestProto.TransportRequestHeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TransportRequestProto.TransportRequestHeader, TransportRequestProto.TransportRequestHeader.Builder, TransportRequestProto.TransportRequestHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 2;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 2;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransportRequest)
    }

    // @@protoc_insertion_point(class_scope:TransportRequest)
    private static final TransportRequestProto.TransportRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TransportRequestProto.TransportRequest();
    }

    public static TransportRequestProto.TransportRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransportRequest>
        PARSER = new com.google.protobuf.AbstractParser<TransportRequest>() {
      @java.lang.Override
      public TransportRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TransportRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransportRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TransportRequestProto.TransportRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransportRequestHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransportRequestHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransportRequestHeader_MetadataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransportRequestHeader_MetadataEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransportRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransportRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!main/proto/TransportRequest.proto\"\200\002\n\026" +
      "TransportRequestHeader\022\021\n\trequestId\030\001 \001(" +
      "\t\022\025\n\roperationType\030\002 \001(\005\022\023\n\013contentType\030" +
      "\003 \001(\005\022\025\n\rauthorization\030\004 \001(\t\022\021\n\tactionUR" +
      "L\030\005 \001(\t\0227\n\010metadata\030\006 \003(\0132%.TransportReq" +
      "uestHeader.MetadataEntry\022\023\n\013convertDesc\030" +
      "\007 \001(\t\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\t:\0028\001\"L\n\020TransportRequest\022\'\n\006he" +
      "ader\030\001 \001(\0132\027.TransportRequestHeader\022\017\n\007p" +
      "ayload\030\002 \001(\014BN\n5com.reabam.framework.bul" +
      "let.transport.common.protocolB\025Transport" +
      "RequestProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TransportRequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransportRequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransportRequestHeader_descriptor,
        new java.lang.String[] { "RequestId", "OperationType", "ContentType", "Authorization", "ActionURL", "Metadata", "ConvertDesc", });
    internal_static_TransportRequestHeader_MetadataEntry_descriptor =
      internal_static_TransportRequestHeader_descriptor.getNestedTypes().get(0);
    internal_static_TransportRequestHeader_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransportRequestHeader_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_TransportRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TransportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransportRequest_descriptor,
        new java.lang.String[] { "Header", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
